name: Update PM2.5 Data

on:
  schedule:
    - cron: "40 3 * * *"   # 00:00 Nepal Time (UTC+5:45)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas requests pyarrow

      - name: Run data fetcher
        env:
          OPENAQ_API_KEY: ${{ secrets.OPENAQ_API_KEY }}
        run: |
          python fetch_pm25_daily.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/pm25_last_14_days.parquet
          git commit -m "Daily PM2.5 update" || echo "No changes"
          git push
